### ISSUE TITLE
【質問】riotxとvuexにおける「ミューテーションとアクションとの関係の違い」について

### ISSUE THREAD

**Issue by ShiMeiWo** [cam-inc/riotx#34]
#### Issue Description
* vuexの場合、「ミューテーションは同期的なステートの変更のために使う。アクションは非同期的な処理結果からミューテションを利用するために使う」と、ミューテーションとアクションとは利用目的による明確な使い分けがありました。一方でriotxは、「ミューテーションでもアクション経由で利用することを推奨」となっています。この違いは、どのような理由で起こっているのでしょうか？

**Comment by cathcheeno** [comment]
>「ミューテーションは同期的なステートの変更のために使う。アクションは非同期的な処理結果からミューテションを利用するために使う」

ドキュメントの書き方言い方の違いがあるだけで、riotxでも↑は当てはまります。ので、vuexとの違いはありませんね。

> 「ミューテーションでもアクション経由で利用することを推奨」

処理の流れが`state` -> `view(riot)` -> `action` -> `mutation` -> `state`となり、viewの役割が
- state通りに描画する
- ユーザアクション発火時にactionをdispatchする
限定されるからです。

**Comment by ShiMeiWo** [comment]
お返事ありがとうございます。

> 処理の流れが`state` -> `view(riot)` -> `action` -> `mutation` -> `state`となり、viewの役割が
> 
> * state通りに描画する
> * ユーザアクション発火時にactionをdispatchする
>
> 限定されるからです。

viewの記述を単純化するため、ということですね。了解いたしました。
疑問が解決いたしましたので、このissueはクローズさせていただきます。

ありがとうございました。
