### ISSUE TITLE
this.riotxChange example

### ISSUE THREAD

**Issue by cgslivre** [cam-inc/riotx#6]
Provides examples using this.riotxChange(appStore.... please

**Comment by cathcheeno** [comment]
@cgslivre 
Sorry for a lack of explanation of riotxChange on README.md. We will put it later.
Anyway, I have just published an example on Codepen. You can check it out [here](https://codepen.io/cathcheeno/pen/JOYZZV).

Leave extra comments if you need more detail.
Thanks.
